name: Lint, Format, and Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

jobs:
  lint-format-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          cd functions
          npm install

      - name: Lint
        run: npm run lint

      - name: Format
        run: |
          npm run check-formatting
          git diff --exit-code || (echo "Code is not formatted correctly. Please run 'npm run format' locally to fix formatting issues." && exit 1)

      - name: Build
        run: npm run build
